
service: strac-drive

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:

  list_files:
    handler: src/files.handler
    events:
      - http:
          path: api/v1/files
          method: GET

  list_file_users:
    handler: src/users.handler
    events:
      - http:
          path: api/v1/file/{file_id}/users
          method: GET

  download_file:
    handler: src/download.handler
    events:
      - http:
          path: api/v1/file/{file_id}/download
          method: GET
