
service: strac-drive

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  stage: ${opt:stage, 'prod'}
  environment: ${file(./env-var.js)}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:

  list_files:
    handler: src/files.handler
    events:
      - http:
          path: api/v1/files
          method: GET

  list_file_users:
    handler: src/users.handler
    events:
      - http:
          path: api/v1/file/{file_id}/users
          method: GET

  subscribe_file_users:
    handler: src/subscribe.handler
    events:
      - http:
          path: api/v1/file/{file_id}/subscribe
          method: POST

  webhook_file_users:
    handler: src/webhook.handler
    events:
      - http:
          path: api/v1/file/{file_id}/webhook
          method: POST

  download_file:
    handler: src/download.handler
    events:
      - http:
          path: api/v1/file/{file_id}/download
          method: GET
